### ISSUE TITLE
Carousel view customization

### ISSUE THREAD

**Issue by hsavit1** [zhangao0086/DKCarouselView#15]
Hello,

It seems as if the carousel view size is set to the bounds of the view, however in my storyboard i only set the height to 250? Any reason why?

Also, is there any way to add subviews to the carousel? Like a UILabel?

Thanks

**Comment by zhangao0086** [comment]
I'm so sorry for the delay reply ...
Can you post the constraints of the carousel view here?

**Comment by hsavit1** [comment]
I have decided to move on from DKCarouselView as I could not get it to function properly

It was in a tableviewheader and the size was constrained to being 250 pts in height.

**Comment by zhangao0086** [comment]
Thanks for taking the time to report this problem, I hope I can fix it in the coming week.
:)

**Comment by msmobileapps** [comment]
problem is with 
customView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight; in the setItems method

**Comment by zhangao0086** [comment]
Fixed in #17.
