### ISSUE TITLE
Make the UIPageControl accessible in interface

### ISSUE THREAD

**Issue by LivioGama** [zhangao0086/DKCarouselView#25]
It is given the possibility to change the currentPageIndicatorTintColor but not the pageIndicatorTintColor. It would be more simple to put the pageControl variable accessible in the .h file

**Comment by manijak** [comment]
I needed this as well, so I created a PR on this. https://github.com/zhangao0086/DKCarouselView/pull/26

**Comment by fjtrujy** [comment]
I think that we can close this issue alrady. The PR: [#26](https://github.com/zhangao0086/DKCarouselView/pull/26) was already merged.

**Comment by zhangao0086** [comment]
Closing this thread.
